version: '3.8'
services:
  api:
    build: .
    container_name: api-comentarios
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - mongo
volumes:
  mongo-data:
