name: Deploy para AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <AWS_ECR_URL>

      - name: Construir e enviar a imagem Docker
        run: |
          docker build -t api-comentarios .
          docker tag api-comentarios:latest <AWS_ECR_URL>:latest
          docker push <AWS_ECR_URL>:latest

      - name: Atualizar serviço ECS
        run: |
          aws ecs update-service --cluster api-cluster --service api-comentarios --force-new-deployment
